name: ui-deploy

on:
  push:
    branches: [ vue ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          npm ci
          npm run build
          cp CNAME docs/CNAME
      - uses: actions-x/commit@v2
